group 'com.heartlandpaymentsystems'
version '2.5.6'

buildscript {
    repositories {
        mavenCentral()
    }
}

repositories {
    mavenCentral()
    maven {
        url 'https://oss.sonatype.org/content/repositories/ksoap2-android-releases/'
    }
}

apply plugin: 'java-library'
apply plugin: 'maven-publish'

sourceCompatibility = 1.7
targetCompatibility = 1.7

sourceSets {
    main {
        java.srcDirs = ['src']
    }
//There are a lot of test failures. Commenting out tests for now.
/*test {
        java.srcDirs = ['tests']
    }*/
}


dependencies {
    implementation group: 'com.google.code.ksoap2-android', name: 'ksoap2-android', version: '3.3.0'
    implementation group: 'commons-codec', name: 'commons-codec', version: '1.8'
    implementation group: 'com.google.code.gson', name: 'gson', version: '2.2.4'
    implementation group: 'org.bouncycastle', name: 'bcprov-jdk14', version: '1.51'

    testImplementation group: 'junit', name: 'junit', version: '4.12'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}

task configureVersion() {
    doFirst {
        if (project.hasProperty("teamcity"))
        {
            def buildNumber = project.teamcity["build.number"]
            version = "${buildNumber}"
        }
        println "Configured the version to ${version}"
    }
}

configureVersion.dependsOn clean
build.dependsOn configureVersion
build.mustRunAfter configureVersion